# Generated by Django 5.0.2 on 2024-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=2500)),
                ('date_text', models.CharField(max_length=2500)),
            ],
        ),
    ]
